/// Flutter icons KriyaIcon
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  KriyaIcon
///      fonts:
///       - asset: fonts/KriyaIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class KriyaIcon {
  KriyaIcon._();

  static const _kFontFam = 'KriyaIcon';

  static const IconData kriya_catalog = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData kriya_home = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData kriya_message = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData kriya_profile = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData kriya_course_1 = const IconData(0xe807, fontFamily: _kFontFam);
}
